---
title: ''
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Der Zeuge
### von Robert Cline
UNM 100684786  
F&uuml;r:  Deutsche Sommerschule von New Mexico - Sprachkurs B2    
Lehrer:  Joseph Kuster  
F&auml;llig: Achtes Essay:  26.06.2023   

## Der Zeuge: Bruch und Umbruch in den turbulenten 60'er Jahre 

Dr. Reiner Rumold, Professor Emeritus Northwestern Universit&auml;t hat am 25. Juni an der deutschen Sommerschule von New Mexico &uuml;ber die turbulenten 60er Jahre gesprochen. Zu dieser Zeit war ich ein Zeuge.  Im Jahr 1964 war ich nur 19 Jahre und befand mich in der Armee.  Ich hatte viel Gl&uuml;ck.  Die Armee hat mich nach Deutschland geschickt.  Viele Freunde gingen nach Viet Nam.  Einige Freunde wünschten nach Viet Nam geschickt zu werden.  Die wollten Krieg erfahren.  Ich nicht.  Ich war sehr froh in Deutschland zu sein.  Ein Fruend von mir war Pazifist. Aufgrund seiner Weigerung nach Vietnam zu gehen verbrachtet er zwei Jahre im Gef&auml;ngnis.    

Lass mich die Geschichte meines Besuchs in Angel Fire erzählen.

Dank den Medien hatte die Realit&auml;t diesen Kreig in jedes Lebenszimmer gebracht. Für jeden war diese Zeit seelisch belastend. Ein Beispiel dafur, wie belastend diese Zeit war, obwohl ich nie im Vietnam gewesen war, nur ein Besuch zum Angel Fire Gedenkort war mir sehr Emotional bewegend.  Als ich 1994 den Angel Fire Genkort besuchte, brach ich zusammen und schluchzte.   Aus ahnlichen emotional bewegenden Gründe wurde die Protestbewegung geboren.  Diese Bewegung wurde als "Hippie-bewegung" bekannt.  Meiner meinung nach war es ein Kult, aber mit intellektuellen, sozialen, politischen, kulturellen und historischen Komponenten.  

Als Soldat konnte ich an die Bewegung kein Teil nehmen.  Aber nach meiner Armeezeit war ich wieder Frei an die Bewegung Teil zu nehmen.  Zu dieser Zeit hatte ich die Hoffnung, dass junge Leute Einfluss auf die Regierung nehmen könnten.  Wir hatten Einfluss aber die Regierung konnten wir nicht andern.  Wir hatten Nixon, wir hatten Kent State wo 4 Studenten toterschossen wurden.  

Hatten wir eine Revolution?  Ja. Aber wie erfolgreich war diese Revolution?  Am Anfang war die Bewegung sehr elfolgreich.   Eine Menge war nur f&uuml;r die Drogen oder sexuale Liberalismus da, d.h. Freiesex; die sogannante Hippiebewegung. Aber junge Leute hatten sich mobilisiert. Sie lernten, wie man Mobilisierung erreichen konnte. Sie forderten eine partizipative Demokratie. Zum Teufel mit Jim Crow; zum Teufel mit Krieg.  

Aber jetzt sind junge Menschen nicht mehr so engagiert beteiligt. Der Idealismus von Gestern wurde von einer anti-wissenschaftlichen Bewegung abgelöst. Der philosophische Modernismus von Alexander Dugin hat die Erzählung der Republikanischen Partei übernommen. Dennoch stehen wir vor einer existenziellen Weltkrise. Es gibt mehr Proteste, mehr Rufe nach Revolution und mehr soziale Gewalt in unserer Zukunft. Schnallen Sie sich an.