---
title: ''
author: ""
date: ""
output: html_document
bibliography: goethe.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 
### von Robert Cline
UNM 100684786  
F&uuml;r:  Deutsche Sommerschule von New Mexico - Sprachkurs B2    
Lehrer:  Joseph Kuster  
F&auml;llig:  Do 29.06.2023  

## Die Große Kompromisslösung 

In einem Vortrag am 9. Juni 2023 auf der Deutschen Sommerschule von New Mexico gehalten, beschrieb Jason Wilby *die Leiden des jungen Werthers* von Goethe [@wilby_goethes_2023]. 

Ich bin kein Goethe scholar.  Ich habe nur von Goethe Faust gelesen.  Ich versuchte *die Leiden des jungen Werthers* zu lesen, aber fand ich ich das Buch zu schwer [@johanes_wolfgang_geothe_leiden_1774].^[die Leiden des jungen Werters ist von Projekt G&uuml;ttenberg-DE kostenlos zum Download verfügbar]  Leider bin ich auch kein Student von Philosophie.  Aber ich bin neuguerig dauber was mir in Goethes Schriften als Widersprüche erscheint.

Wilby malte ein Bild von Goethe, als er sein Schaffen als einen Umbruch mit der Aufklärung erklärte. Mit seinem kreativen Schaffen hat Goethe eine neue Ära des Romantizismus hervorgebracht. Laut Wilby, Laut Wilby schrieb Goethe:

*Man kann zum Vortheile der Regeln viel sagen, ohngef&auml;hr was man zum Lobe der b&uuml;rgerlichen Gesellschaft sagen kann.  Ein Mensch, der sich nach ihnen bilden, wird nie etwas abgeschmacktes und schlechtes hervorbringen...dagegen wird aber auch alle Regel, man rede was man wolle, das wahre Gef&uuml;hl von Natur und den wahren Ausdruck derselben zerst&ouml;ren.*

Hier stellt Goethe soziale Zwänge als schädlich für die Seele.  Jetzt kommt der junge Werther verlassen und untröstlich von unerwidertet Liebe.  Werther befand sich in solchem Leid und solcher Trauer, dass er Selbstmord begehen musste. Werther lehnt gesellschaftliche Normen ab und verbindet sich mit idealistischem Romantizismus. Er erliegt ihnen.

Im Widerspruch zur Verehrung des Romantizismus seiner Zeit, erliegt Goethe ebenfalls. Er schrieb seine Geschichte um. Nur in der ersten Ausgabe bleibt Goethe seinen Überzeugungen treu.

**Andere Resourzen**: 

* Sturm und Drang, d.h. Counter Enlightenment [@wikipedia_sturm_2023] 
* Romanticismus  [@turlington_unit_2021]
References: 